### ISSUE TITLE
Should probably add a license statement to this repo

### ISSUE THREAD

**Issue by tom-anders** [davidbauch/QDLC-C#1]
I'm currently cleaning up the old code for my master thesis and want to publish it as a new public repo on my profile. I still have your old Loadbar.h header in there - Is it ok for you if I just include a link to QDLC-C somewhere in my README?

**Comment by davidbauch** [comment]
> I'm currently cleaning up the old code for my master thesis and want to publish it as a new public repo on my profile. I still have your old Loadbar.h header in there - Is it ok for you if I just include a link to QDLC-C somewhere in my README?

Sure! Sorry for the late reply ¯\_(ツ)_/¯

**Comment by tom-anders** [comment]
<3 :D
